/**
 * Identificador de Tipos de Ativos
 * Determina se um ativo é Chain, Protocol ou Token
 */

// Lista de chains conhecidas (Layer 1)
export const KNOWN_CHAINS = new Set([
  // Major L1s
  'bitcoin', 'btc',
  'ethereum', 'eth',
  'solana', 'sol',
  'cardano', 'ada',
  'polkadot', 'dot',
  'avalanche', 'avax',
  'polygon', 'matic',
  'binance', 'bnb', 'bsc',
  'arbitrum', 'arb',
  'optimism', 'op',
  'base',
  'fantom', 'ftm',
  'near',
  'cosmos', 'atom',
  'tron', 'trx',
  'aptos', 'apt',
  'sui',
  'sei',
  'celestia', 'tia',
  'injective', 'inj',
  'thorchain', 'rune',
  'kava',
  'osmosis', 'osmo',
  'juno',
  'evmos',
  'cronos', 'cro',
  'algorand', 'algo',
  'tezos', 'xtz',
  'elrond', 'egld', 'multiversx',
  'hedera', 'hbar',
  'iota', 'miota',
  'vechain', 'vet',
  'eos',
  'neo',
  'waves',
  'stellar', 'xlm',
  'monero', 'xmr',
  'zcash', 'zec',
  'dash',
  'decred', 'dcr',
  'digibyte', 'dgb',
  'ravencoin', 'rvn',
  'zilliqa', 'zil',
  'ontology', 'ont',
  'icon', 'icx',
  'qtum',
  'lisk', 'lsk',
  'ark',
  'nano',
  'iost',
  'theta',
  'wanchain', 'wan',
  'aion',
  'aeternity', 'ae',
  'nebulas', 'nas',
  'stacks', 'stx',
  'harmony', 'one',
  'celo',
  'flow',
  'moonbeam', 'glmr',
  'moonriver', 'movr',
  'aurora',
  'gnosis', 'gno',
  'metis',
  'boba',
  'syscoin', 'sys',
  'conflux', 'cfx',
  'elastos', 'ela',
  'nervos', 'ckb',
  'kadena', 'kda',
  'casper', 'cspr',
  'mina',
  'oasis', 'rose',
  'secret', 'scrt',
  'fetch', 'fet',
  'ocean', 'ocean',
  'kusama', 'ksm',
  'acala', 'aca',
  'moonbase',
  'astar',
  'shiden',
  'kilt',
  'parallel',
  'clover',
  'everdome',
  'dogechain',
  'flare',
  'songbird',
  'xrp', 'ripple',
  'litecoin', 'ltc',
  'bitcoin-cash', 'bch',
  'ethereum-classic', 'etc',
  'filecoin', 'fil',
  'chainlink', 'link', // LINK pode ser ambíguo
  'uniswap', 'uni', // UNI pode ser ambíguo
  'internet-computer', 'icp',
  'the-graph', 'grt',
  'sandbox', 'sand',
  'decentraland', 'mana',
  'axie', 'axs',
  'enjin', 'enj',
  'gala',
  'immutable', 'imx',
  'wemix',
  'ronin',
  'lukso',
  'blast',
  'scroll',
  'linea',
  'zksync',
  'starknet', 'strk',
  'loopring', 'lrc',
  'polygon-zkevm',
  'taiko',
  'aztec',
  'manta',
  'mantle', 'mnt',
  'mode',
  'zora',
  'xlayer',
  'merlin',
  'berachain', 'bera',
  'zetachain', 'zeta',
  'wemix',
  'kroma',
  'rootstock', 'rsk', 'rbtc',
  'lightlink',
  'core',
  'velas', 'vlx',
  'telos', 'tlos',
  'godwoken',
  'bittorrent', 'btt',
  'heco', 'ht',
  'okex', 'okb', 'okc',
  'kucoin', 'kcs',
  'fuse',
  'energi', 'nrg',
  'thundercore', 'tt',
  'tomochain', 'tomo',
  'smartbch',
  'viction', 'vic',
  'metadium', 'meta',
  'kardia', 'kai',
]);

// Lista de protocolos DeFi conhecidos (não são chains)
export const KNOWN_PROTOCOLS = new Set([
  'aave',
  'compound',
  'maker', 'makerdao',
  'curve',
  'convex',
  'lido',
  'rocket-pool', 'rocketpool',
  'frax',
  'liquity',
  'yearn',
  'synthetix',
  'gmx',
  'gains',
  'dydx',
  'pancakeswap',
  'sushiswap',
  'balancer',
  'velodrome',
  '1inch',
  'kyber',
  'paraswap',
  'stargate',
  'synapse',
  'across',
  'hop',
  'celer',
  'multichain',
  'wormhole',
  'layerzero',
  'benqi',
  'trader-joe', 'traderjoe',
  'platypus',
  'vector',
  'radiant',
  'venus',
  'justlend',
  'geist',
  'cream',
  'iron-bank', 'ironbank',
  'rari',
  'euler',
  'morpho',
  'spark',
  'abracadabra',
  'olympus', 'ohm',
  'reflexer', 'rai',
  'fei',
  'tribe',
  'alchemix',
  'spell',
  'mim',
  'tokemak',
  'ribbon',
  'opyn',
  'hegic',
  'lyra',
  'dopex',
  'jones',
  'umami',
  'camelot',
  'ramses',
  'chronos',
  'thena',
  'equalizer',
]);

/**
 * Identifica o tipo de ativo baseado no nome/query
 */
export function identifyAssetType(query: string): 'chain' | 'protocol' | 'token' {
  const normalized = query.toLowerCase().trim();

  // Verificar se é chain conhecida
  if (KNOWN_CHAINS.has(normalized)) {
    return 'chain';
  }

  // Verificar se é protocolo conhecido
  if (KNOWN_PROTOCOLS.has(normalized)) {
    return 'protocol';
  }

  // Se não souber, assumir que é token por padrão
  // A lógica de agregação vai tentar descobrir depois
  return 'token';
}

/**
 * Verifica se um ativo é uma chain
 */
export function isChain(query: string): boolean {
  return identifyAssetType(query) === 'chain';
}

/**
 * Verifica se um ativo é um protocolo DeFi
 */
export function isProtocol(query: string): boolean {
  return identifyAssetType(query) === 'protocol';
}

/**
 * Normaliza nome de chain para match com APIs
 */
export function normalizeChainName(name: string): string {
  const normalized = name.toLowerCase().trim();

  const mappings: Record<string, string> = {
    'btc': 'Bitcoin',
    'eth': 'Ethereum',
    'sol': 'Solana',
    'ada': 'Cardano',
    'dot': 'Polkadot',
    'avax': 'Avalanche',
    'matic': 'Polygon',
    'bnb': 'BSC',
    'bsc': 'BSC',
    'arb': 'Arbitrum',
    'op': 'Optimism',
    'ftm': 'Fantom',
    'atom': 'Cosmos',
    'trx': 'Tron',
    'apt': 'Aptos',
    'cro': 'Cronos',
    'algo': 'Algorand',
    'xtz': 'Tezos',
    'egld': 'Elrond',
    'hbar': 'Hedera',
    'vet': 'Vechain',
    'xlm': 'Stellar',
    'xmr': 'Monero',
    'zec': 'Zcash',
    'zil': 'Zilliqa',
    'ont': 'Ontology',
    'icx': 'Icon',
    'one': 'Harmony',
    'glmr': 'Moonbeam',
    'movr': 'Moonriver',
    'gno': 'Gnosis',
    'sys': 'Syscoin',
    'cfx': 'Conflux',
    'ela': 'Elastos',
    'ckb': 'Nervos',
    'kda': 'Kadena',
    'cspr': 'Casper',
    'rose': 'Oasis',
    'scrt': 'Secret',
    'fet': 'Fetch',
    'ksm': 'Kusama',
    'aca': 'Acala',
    'xrp': 'Ripple',
    'ltc': 'Litecoin',
    'bch': 'Bitcoin Cash',
    'etc': 'Ethereum Classic',
    'fil': 'Filecoin',
    'icp': 'Internet Computer',
    'grt': 'The Graph',
    'sand': 'Sandbox',
    'mana': 'Decentraland',
    'axs': 'Axie',
    'enj': 'Enjin',
    'imx': 'Immutable',
    'strk': 'Starknet',
    'lrc': 'Loopring',
    'mnt': 'Mantle',
    'bera': 'Berachain',
    'zeta': 'Zetachain',
    'vlx': 'Velas',
    'tlos': 'Telos',
    'btt': 'Bittorrent',
    'ht': 'Heco',
    'okb': 'OKEx',
    'kcs': 'Kucoin',
    'nrg': 'Energi',
    'tt': 'ThunderCore',
    'tomo': 'TomoChain',
    'vic': 'Viction',
    'kai': 'Kardia',
    'rbtc': 'Rootstock',
  };

  return mappings[normalized] || name.charAt(0).toUpperCase() + name.slice(1);
}
